require("config.comment")
require("config.glow")
require("config.tree")
require("config.treesitter")
require("config.spellsitter")
require("config.telescope")
require("config.completion")
require("config.lsp")
