require("config.gitsigns")
require("config.tree")
require("config.completion")
require("config.mason")
require("config.lspconfig")
require("config.null_ls")
require("config.telescope")
require("config.treesitter")
